name: dcms_1
description: "Dental clinic management system for Arab American University Jenin"
publish_to: 'AAUP'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^3.13.0
  firebase_auth: ^5.0.0
  firebase_storage: ^12.0.0
  cloud_firestore: ^5.0.0
  firebase_database: ^11.3.5

  intl: ^0.19.0
  provider: ^6.1.4
  connectivity_plus: ^6.1.3
  font_awesome_flutter: ^10.8.0  # Check for web compatibility, might need conditional import or a different package.
  url_launcher: ^6.2.0 # Works on web.
  cupertino_icons: ^1.0.8 # Primarily for iOS, but won't cause issues on other platforms.
  image_picker: ^1.1.2 # Check if this version works on web.
  image: ^4.5.4 # Should be fine.
  flutter_image_compress: ^2.0.0 # Check for web compatibility.
  cached_network_image: ^3.2.3
  camera: ^0.11.1 # Android and iOS only. Consider conditional import or platform-specific code.
  
  permission_handler: ^12.0.0+1
  path_drawing: ^1.0.0
  xml: ^6.2.0
  sqflite: ^2.2.0
  http: ^0.13.6
  universal_html: ^2.2.1 
  shared_preferences: ^2.5.3
  tflite_flutter: ^0.11.0
  google_mlkit_face_detection: ^0.13.1
  showcaseview: ^4.0.1
  firebase_messaging: ^15.2.7
  flutter_local_notifications: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  generate: true

  
 

  assets:
    - ./lib/assets/aauplogo.png
    - ./lib/assets/logo1.png
    - ./lib/assets/backgrownd.png
